-- change some columns and tables titles
alter table restaurants_bookings change created_at restaurants_bookings_created_at datetime default now();
alter table restaurants_bookings change updated_at restaurants_bookings_updated_at datetime default now();
alter table restaurants_bookings change closed_at restaurants_bookings_closed_at datetime default now();
alter table restaurants_payments change created_at restaurants_payments_created_at datetime default now();
alter table restaurants_payments change updated_at restaurants_payments_updated_at datetime default now();
alter table hotels_bookings change created_at hotels_bookings_created_at datetime default now();
alter table hotels_bookings change updated_at hotels_bookings_updated_at datetime default now();
alter table hotels_bookings change closed_at hotels_bookings_closed_at datetime default now();
alter table hotels_payments change created_at hotels_payments_created_at datetime default now();
alter table hotels_payments change updated_at hotels_payments_updated_at datetime default now();
rename table user_type to users_types;
rename table enterprise_type to enterprises_types;
rename table enterprise_profile to enterprises_profiles;
alter table enterprises_profiles change operations_country operation_country varchar(100);
alter table tourism.enterprises_profiles change operations_city operation_city varchar(100) character set utf8mb4 collate utf8mb4_0900_ai_ci not null;
alter table tourism.media change photo_albums photo_album longblob null;
alter table tourism.enterprises_profiles change operations_street operation_street varchar(100) character set utf8mb4 collate utf8mb4_0900_ai_ci not null;
alter table tourism.enterprises_profiles change operations_house_number operation_house_number int not null;
alter table tourism.restaurants change restaurants_categories restaurant_category set('russian cuisine','cafe','sushi','stake house','seafood','pizza','chinese cuisine','italian cuisine') character set utf8mb4 collate utf8mb4_0900_ai_ci null;
alter table tourism.restaurants change restaurants_features restaurant_feature set('for families with childrens','romantic','picturistique view','for business','for friends') character set utf8mb4 collate utf8mb4_0900_ai_ci null;
alter table tourism.restaurants_bookings change restaurants_bookings_created_at restaurant_booking_created_at datetime default current_timestamp;
alter table tourism.restaurants_bookings change restaurants_bookings_updated_at restaurant_booking_updated_at datetime default current_timestamp;
alter table tourism.restaurants_bookings change restaurants_bookings_closed_at restaurant_booking_closed_at datetime default current_timestamp;
alter table tourism.hotels_bookings change hotels_bookings_created_at hotel_booking_created_at datetime default current_timestamp;
alter table tourism.hotels_bookings change hotels_bookings_updated_at hotel_booking_updated_at datetime default current_timestamp;
alter table tourism.hotels_bookings change hotels_bookings_closed_at hotel_booking_closed_at datetime default current_timestamp;
alter table tourism.hotels_bookings change hotels_profile_id hotel_profile_id bigint unsigned not null;
alter table tourism.restaurants_bookings change restaurants_profile_id restaurant_profile_id bigint unsigned not null;
alter table tourism.enterprises_profiles change from_operations_hours from_operation_hour time null;
alter table tourism.enterprises_profiles change to_operations_hours to_operation_hour time null;
alter table tourism.hotels change hotels_media_id hotel_media_id bigint unsigned not null;
alter table tourism.hotels_cashback change total_hotels_cashback total_hotel_cashback decimal(15,2) null;
alter table tourism.restaurants_cashback change total_restaurants_cashback total_restaurant_cashback decimal(15,2) unsigned null;
alter table tourism.restaurants_payments change restaurants_payments_created_at restaurant_payment_created_at datetime default current_timestamp;
alter table tourism.restaurants_payments change restaurants_payments_updated_at restaurant_payment_updated_at datetime default current_timestamp;
alter table tourism.hotels_payments change hotels_payments_created_at hotel_payment_created_at datetime default current_timestamp;
alter table tourism.hotels_payments change hotels_payments_updated_at hotel_payment_updated_at datetime default current_timestamp;